routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();
Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController');
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
// show request
    Route::get('users/show-request/{user}', [
        'uses'=>'UserController@showRequest',
        'as'=>'showRequest',
        'middleware'=>'roles',
        'roles'=>['superAdmin'],
    ]);
//user's password edit request
    Route::put('user/password/edit', [
        'uses'=>'UserController@editPassword',
        'as'=>'edit.password',
        'middleware'=>'roles',
        'roles'=>['admin','superAdmin'],
    ]);
    Route::put('user/password/update', [
        'uses'=>'UserController@updatePassword',
        'as'=>'update.password',
        'middleware'=>'roles',
        'roles'=>['superAdmin'],
    ]);
// delete edit request
    Route::delete('users/editRequest/{id}/delete', [
        'uses'=>'UserController@deleteRequest',
        'as'=>'deleteRequest',
        'middleware'=>'roles',
        'roles'=>['superAdmin'],
    ]);
//show user group request
    Route::get('group/{user}/request', [
        'uses'=>'UserController@userGroupsRequest',
        'as'=>'userGroupsRequest',
        'middleware'=>'roles',
        'roles'=>['superAdmin'],
    ]);
// Approve request update group
    Route::post('group/request/approve', [
        'uses'=>'UserController@activeUserGroups',
        'as'=>'approve.request',
        'middleware'=>'roles',
        'roles'=>['superAdmin'],
    ]);
// delete password request
    Route::delete('users/passwordRequest/delete',[
        'uses'=>'UserController@deletePasswordRequest',
        'as'=>'deletePasswordRequest',
        'middleware'=>'roles',
        'roles'=>['superAdmin'],
    ]);

   Route::group(['middleware'=>'roles','roles'=>['admin','superAdmin']],function (){
       // add user to group
       Route::get('groups/{room}/group_users','ChatController@groupUser')->name('group_user');
       // update user's groups
       Route::get('user/{user}/group_update','UserController@updateGroupsView')->name('updateGroupUserView');
       Route::post('user/{user}/group_updated','UserController@updateGroups')->name('updateGroupUser');
   });
   Route::group(['middleware'=>'roles','roles'=>['superAdmin']],function (){
      Route::get('users/update/requests','UserController@userUpdateRequests')
          ->name('userUpdateRequests');
      Route::get('user/update/password/requests','UserController@userUpdatePasswordRequests')
          ->name('userPasswordRequests');
       Route::get('user/update/groups/requests','UserController@indexUserGroupRequests')
           ->name('indexUserGroupRequests');
       Route::delete('user/update/groups/requests/delete','UserController@deleteGroupRequest')
           ->name('deleteGroupRequest');
   });

});
// request for edit
Route::post('edit-request','UserController@createRequest')->name('createRequest');
// Role Routes
Route::resource('roles','RolesController');
// Last News Routes
Route::resource('lastNews','LastNewsController')->except(['destroy']);
Route::delete('lastNews/{post}/delete','LastNewsController@destroy')->name('lastNews.delete');
// Section Routes
Route::resource('section','SectionController');
// About Routes
Route::resource('about','AboutController');
// Question Routes
Route::resource('questions','FaqController');
// Chat Routes
Route::resource('Chat','ChatController');
Route::get('/chat.show/{id}',[\App\Http\Controllers\ChatController::class, 'show'])->name('groupName');
Route::get('/conve/{code}',[\App\Http\Controllers\UserController::class, 'conversation'])->name('conversation');
Route::get('/D/{id}',function ($id){
    $getById = \App\Models\Chatroom::find($id);
    $getById->delete();
    return redirect()->back()->withstatus(__('Room Deleted'));
});
Route::get('/editRoom/{id}',[\App\Http\Controllers\ChatController::class, 'editRoom'])->name('editRoom');
Route::post('/editRoom/{id}',[\App\Http\Controllers\ChatController::class, 'editRoom'])->name('editRoom');
Route::post('/activeRoom/{id}',[\App\Http\Controllers\ChatController::class, 'activeRoom'])->name('activeRoom');
//private chat route
Route::get('/messages',[\App\Http\Controllers\UserController::class ,'messages'])->name('messages');
// Answers Routes
Route::get('answers/{answer}/show','FaqController@showAnswer')->name('answer.show');
Route::get('answers/{answer}/edit','FaqController@editAnswer')->name('answer.edit');
Route::put('answers/{answer}/update','FaqController@updateAnswer')->name('answer.update');
Route::get('answers/{question}/create','FaqController@createAnswer')->name('answer.create');
Route::post('answers/store','FaqController@storeAnswer')->name('answer.store');
Route::delete('answers/{answer}/delete','FaqController@destroyAnswer')->name('answer.delete');
//procedure types
Route::resource('procedureType', 'ProcedureTypeController');
//student requests
Route::resource('studentRequest', 'StudentRequestController')->except(['index']);
Route::post('studentRequest/forward_to/{studentRequest}', 'StudentRequestController@forward')->name('studentRequest.forward');
Route::post('studentRequest/done/{studentRequest}','StudentRequestController@done')->name('done');
Route::get('studentRequests','StudentRequestController@adminIndex')->name('request.admin');
Route::get('studentRequest',[
    'uses'=>'StudentRequestController@index',
    'as'=>'studentRequest.index',
    'middleware'=>'roles',
    'roles'=>['superAdmin']
]);
//chat request
Route::resource('chatRequests','ChatRequestController');
Route::post('chatRequest/confirm/{chatRequest}','ChatRequestController@confirm')->name('chatRequest.confirm');
// Hdr Routes
Route::resource('hrd','HrdController');
// Groups Routes
Route::resource('groups','UserGroupsController');
//excel
Route::get('file-import-export', 'UserController@fileImportExport');
Route::post('file-import', 'UserController@fileImport')->name('file-import');
Route::get('file-export', 'UserController@fileExport')->name('file-export');
//lang
Route::get('lang/{lang}', 'LanguageController@swap')->name('lang');
Route::post('notify',[\App\Http\Controllers\ChatController::class, 'notification'])->name('notification');
//reports
Route::get('reports','UserController@counter')->name('reports');

app/Http/Controllers/Api/ChatController.php
<?php

namespace App\Http\Controllers\Api;

use App\Events\notifications\NotificationCreatedEvent;
use App\Http\Controllers\Controller;
use App\Models\Notification;
use Illuminate\Http\Request;
use App\Http\Resources\GroupResource;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use App\Models\user_groups;
use App\Models\Chatroom;
use App\User;

class ChatController extends Controller
{
    public function __construct()
    {
        $this->middleware('guest')->only(['index', 'sendNotification', 'sendNotificationGroup']);
    }

    public function index()
    {
        return GroupResource::collection(\App\Models\Chatroom::paginate(10));
    }


    public function createGroup(Request $request)
    {

        $validator = Validator::make($request->all(), [
            'name' => 'required|string:max:255',
            'code' => 'required|min:3',
            'image' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);
        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()], 400);
        }

        $rooms = new Chatroom();
        if ($request->hasFile('image')) {
            $image = $request->image;
            $groupImage = $this->UploadImage($image);
        } else {
            $groupImage = 'default.png';
        }
        if ($request->selectDays == 1) {
            $days = "Saturday | Monday | Wednesday";
        } else if ($request->selectDays == 2) {
            $days = "Sunday | Tuesday | Thursday";
        }

        if (auth()->user()->hasRole('superAdmin')) {
            $status = 1;

        } else if (auth()->user()->hasRole('admin')) {
            $status = 0;
        }
        $rooms->groupName = $request->name;
        $rooms->code = $request->code;
        $rooms->days = $days;
        $rooms->daysId = $request->selectDays;
        $rooms->timeFrom = $request->timeFrom;
        $rooms->timeTo = $request->timeTo;
        $rooms->image = $groupImage;
        $rooms->status = $status;
        $rooms->save();
        $userGroup = new user_groups();
        $userGroup->user_id = $request->teacher_id;
        $userGroup->group_id = $rooms->id;
        $userGroup->save();
        if ($rooms) {
            return response()->json('Group Created', 200);
        }
    }

    //send notification

    public function sendNotification(Request $request)
    {
        //notification structure
        $sender_id = $request->sender_id;
        $sender = User::where('id', $sender_id)->first();
        $message = 'New message from ' . $sender->name;
        $receiver_id = $request->receiver_id;
        $notification = Notification::create([
            'title' => 'New Message !',
            'text' => $message,
            'user_id' => $receiver_id,
        ]);
        event(new NotificationCreatedEvent($notification, $receiver_id));
        return response()->json('success', 200);
    }

    //send notification to a group
    public function sendNotificationGroup(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'group_id' => 'required',
            'sender_id' => 'required'
        ]);
        if ($validator->fails()) {
            return response()->json(['error' => $validator->errors()], 400);
        }
        $sender_id = $request->sender_id;
        $sender = User::where('id', $sender_id)->first();
        $group = Chatroom::where('id', $request->group_id)->first();
        $users = user_groups::where('group_id', $request->group_id)->where('user_id', '<>', $sender_id)->select('user_id')->get();
        foreach ($users as $user) {
            $receiver_id = $user->user_id;
            $message = 'New message from ' . $sender->name . ' in group ' . $group->groupName;
            $notification = Notification::create([
                'title' => 'New Message !',
                'text' => $message,
                'user_id' => $receiver_id,
            ]);
            event(new NotificationCreatedEvent($notification, $receiver_id));
        }
        return response()->json('success', 200);
    }

public
function UploadImage($image)
{
    //get file name with extention
    $filenameWithExt = $image->getClientOriginalName();
    //get just file name
    $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
    //GET EXTENTION
    $extention = $image->getClientOriginalExtension();
    //file name to store
    $fileNameToStore = $filename . '_' . time() . '.' . $extention;
    //upload image
    $path = $image->storeAs('public/images/groups/', $fileNameToStore);
    return $fileNameToStore;
}

public
function notification(Request $request)
{
    if ($request->userId != auth()->user()->id) {
        if ((auth()->user()->role->id < 3) || (auth()->user()->id * 1000000 == $request->roomId)) {
            console . log('here');
            echo '<script>alert("here")</script>';
        }
    }

}


//	    public function alert($name){
//        echo"<script>alert('$name')</script>";
//    }
//
//    public function enterName($name){
//    echo"
//    <script src='".asset("chatcord")."/public/js/jquery.js'></script>
//    <script src='".asset("chatcord")."/public/js/socket.io.js'></script>
//    <script>
//        var io = io('http://127.0.0.1:3000');
//        io.emit('user_connected', '".$name."');
//        sender = '".$name."';
//        alert('".$name."');
//    </script>";
//    }
//
//    //Lister to user from server
//    public function ListenUser(){
//        echo"<script src='".asset("chatcord")."/public/js/jquery.js'></script>
//    <script src='".asset("chatcord")."/public/js/socket.io.js'></script>
//    <script>
//        var io = io('http://127.0.0.1:3000');
//        io.on('user_connected', function (username) {
//            alert(username);
//        });
//    </script>";
//    }
}

app/Http/Controllers/ChatController.php
<?php

namespace App\Http\Controllers;

use App\Models\user_groups;
use App\User;
use Illuminate\Http\Request;
use App\Models\Chatroom;
use Illuminate\Support\Facades\DB;

class ChatController extends Controller
{
    public function index()
    {
        $rooms = Chatroom::orderBy('created_at','desc')->get();
        return view('chat.index', compact('rooms'));
    }

    public function create()
    {
        $teachers=User::where('role_id',4)->get();
        return view('chat.create',compact('teachers'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string:max:255',
            'code' => 'required|min:3',
        ]);
        $rooms = new Chatroom();
        if ($request->selectDays == 1){
            $days = "Saturday | Monday | Wednesday";
        }else if ($request->selectDays == 2 ){
            $days = "Sunday | Tuesday | Thursday";
        }

        if (auth()->user()->hasRole('superAdmin')){
            $status = 1;

        }else if (auth()->user()->hasRole('admin')){
            $status = 0;
        }
        if($request->timeFrom > $request->timeTo){
            return redirect()->back()->withstatus(__("alerts.backend.group.validate_time"));
        }
        $rooms->groupName = $request->name;
        $rooms->code = $request->code;
        $rooms->days = $days;
        $rooms->daysId = $request->selectDays;
        $rooms->timeFrom = $request->timeFrom;
        $rooms->timeTo = $request->timeTo;
        $rooms->status = $status;
        $rooms->save();
        if ($request->teachers) {
            foreach ($request->teachers as $teacher) {
                $userGroup = new user_groups();
                $userGroup->user_id = $teacher;
                $userGroup->group_id = $rooms->id;
                $userGroup->save();
            }
        }
        return redirect(route('Chat.index'))->withstatus(__('alerts.backend.group.created' ));
    }

    public function show($id)
    {
        $group = ChatRoom::findOrFail($id);
        $arr = array('thisGroup' => $group);

        return view('chat.show', $arr);
    }

    public function editRoom(Request $request, $id)
    {
        $method = $request->method();
        echo $method;
        if ($request->isMethod('post')) {
            $editRoom = ChatRoom::findOrFail($id);
            if ($request->hasFile('image')) {
                $image = $request->image;
                $groupImage = $this->UploadImage($image);
            } else {
                $groupImage = $editRoom->image;
            }

            if ($request->selectDays == 1){
                $days = "Saturday | Monday | Wednesday";
            }else if ($request->selectDays == 2 ){
                $days = "Sunday | Tuesday | Thursday";
            }

            $editRoom->groupName = $request->name;
            $editRoom->code = $request->code;
            $editRoom->days = $days;
            $editRoom->daysId = $request->selectDays;
            $editRoom->timeFrom = $request->timeFrom;
            $editRoom->timeTo = $request->timeTo;
            $editRoom->image =$groupImage;
            $editRoom->save();
            return redirect(route('Chat.index'))->withstatus(__('alerts.backend.group.updated'));
        } else {
            $editRoom = ChatRoom::findOrFail($id);
            $arr = array('roomView' => $editRoom);
            return view('chat.edit', $arr);
        }
    }

    public function groupUser(Chatroom $room)
    {
        $userGroup=user_groups::where('group_id',$room->id)->paginate(10);
        return view('chat.groupUser', compact('room','userGroup'));
    }
    public function UploadImage($image)
    {
        //get file name with extention
        $filenameWithExt = $image->getClientOriginalName();
        //get just file name
        $filename = pathinfo($filenameWithExt, PATHINFO_FILENAME);
        //GET EXTENTION
        $extention = $image->getClientOriginalExtension();
        //file name to store
        $fileNameToStore = $filename . '_' . time() . '.' . $extention;
        //upload image
        $path = $image->storeAs('public/images/groups/', $fileNameToStore);
        return $fileNameToStore;
    }

    public function activeRoom($id){
        $group = ChatRoom::findOrFail($id);
        $group->status = 1;
        $group->save();

                    $userGroup = new user_groups();
                    $userGroup->user_id = auth()->user()->id;
                    $userGroup->group_id = $id;
                    $userGroup->save();

        return redirect(route('Chat.index'))->withstatus(__('Group is activated now'));
    }
        public function notification(){


//        if ($request->userId != auth()->user()->id){
//            if ((auth()->user()->role->id < 3)||(auth()->user()->id * 1000000 == $request->roomId)){
//                console.log ('here');
//            }
//        }
        echo'
        <script>
            alert("here");
        </script>
        ';
        return response()->json('ss', 200);
    }

}

resources/views/chat/create.blade.php
@extends('layouts.app', ['name' => __('Create Room')])

@section('content')
    @include('chat.partials.header', [

        'class' => 'col-lg-12'
    ])
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-8 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <h3 class="col-12 mb-0">@lang('labels.backend.access.groups.create')</h3>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{route('Chat.store')}}" method="post" enctype="multipart/form-data">
                            @method('POST')
                            @csrf
                            <h6 class="heading-small text-muted mb-4">@lang('labels.backend.access.groups.group-information')</h6>
                            <div class="col-12">
                                @if (session('status'))
                                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                                        {{ session('status') }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @endif
                            </div>
                            <div class="col-12">
                                @if($errors->any())
                                    @foreach($errors->all() as $error)
                                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                            {{$error}}
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                    @endforeach
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                <label for="name">@lang('labels.backend.access.groups.name')</label>
                                <input name="name" type="text"
                                       class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                       id="name"
                                       placeholder="Group name"
                                       required>
                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('code') ? ' has-danger' : '' }}">
                                <label for="code">@lang('labels.backend.access.groups.code')</label>
                                <input name="code" type="text"
                                       class="form-control form-control-alternative{{ $errors->has('code') ? ' is-invalid' : '' }}" id="code"
                                       placeholder="code"
                                       required>
                                @if ($errors->has('code'))
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('code') }}</strong>
                                        </span>
                                @endif
                            </div>
                            <div name="ddDays" class="dropdown form-group{{ $errors->has('days') ? ' has-danger' : '' }}">
                                <label for="days">@lang('labels.backend.access.groups.days')</label>
                                <select name="selectDays" class="form-control selectpicker" data-style="btn btn-link" id="selectDays">
                                    <option value="1" class="dropdown-item">Saturday | Monday | Wednesday</option>
                                    <option value="2" class="dropdown-item">Sunday | Tuesday | Thursday</option>
                                </select>
                                @if ($errors->has('days'))
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('days') }}</strong>
                                        </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('time') ? ' has-danger' : '' }}">
                                <label for="time">@lang('labels.backend.access.groups.times')</label>
                                    <div class="form-group" style="width: fit-content;">
                                        <label for="example-time-input" class="form-control-label">From</label>
                                        <input name="timeFrom" class="form-control" type="time" value="10:30" id="example-time-input">
                                    </div>
                                    <div class="form-group" style="width: fit-content;">
                                        <label for="example-time-input" class="form-control-label">To</label>
                                        <input name="timeTo" class="form-control" type="time" value="10:30" id="example-time-input">
                                    </div>
                                @if ($errors->has('time'))
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('time') }}</strong>
                                        </span>
                                @endif
                            </div>
                            <div class="row">
                                <div class="col-md-12" id="group" >
                                    <div class="form-group{{ $errors->has('group') ? ' has-danger' : '' }}">
                                        <div class="form-group">
                                            <label for="groupSelect">@lang('labels.backend.access.users.add-group')</label>
                                            <select name="teachers[]" class="js-example-basic-multiple"
                                                    data-style="btn btn-link"
                                                    id="groupSelect" multiple>
                                                <option disabled value=""></option>
                                                @foreach($teachers as $teacher)
                                                    <option value="{{$teacher->id}}">{{$teacher->name}}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    @if ($errors->has('group'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('group') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-success btn-lg ">@lang('buttons.general.crud.create')</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        @include('layouts.footers.auth')
    </div>
    <script src="{{asset('nodejsapp/js/jquery.js')}}" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            $('.js-example-basic-multiple').select2({
                width: '400px'
            });
        });
    </script>
@endsection

resources/views/chat/groupUser.blade.php
@extends('layouts.app', ['name' => __('Add User To Group')])

@section('content')
    @include('chat.partials.header', [
        'class' => 'col-lg-12'
    ])
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">

                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="example" class="table align-items-center table-flush">
                                <thead class="thead-light">
                                <tr>
                                    <th scope="col">@lang('labels.backend.access.users.main')</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($userGroup as $user)
                                    <tr>
                                        <td>
                                            {{$user->user->name}}
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @include('layouts.footers.auth')
    </div>

@endsection