routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();
Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController');
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
// show request
    Route::get('users/show-request/{user}', [
        'uses'=>'UserController@showRequest',
        'as'=>'showRequest',
        'middleware'=>'roles',
        'roles'=>['superAdmin'],
    ]);
//user's password edit request
    Route::put('user/password/edit', [
        'uses'=>'UserController@editPassword',
        'as'=>'edit.password',
        'middleware'=>'roles',
        'roles'=>['admin','superAdmin'],
    ]);
    Route::put('user/password/update', [
        'uses'=>'UserController@updatePassword',
        'as'=>'update.password',
        'middleware'=>'roles',
        'roles'=>['superAdmin'],
    ]);
// delete edit request
    Route::delete('users/editRequest/{id}/delete', [
        'uses'=>'UserController@deleteRequest',
        'as'=>'deleteRequest',
        'middleware'=>'roles',
        'roles'=>['superAdmin'],
    ]);
//show user group request
    Route::get('group/{user}/request', [
        'uses'=>'UserController@userGroupsRequest',
        'as'=>'userGroupsRequest',
        'middleware'=>'roles',
        'roles'=>['superAdmin'],
    ]);
// Approve request update group
    Route::post('group/request/approve', [
        'uses'=>'UserController@activeUserGroups',
        'as'=>'approve.request',
        'middleware'=>'roles',
        'roles'=>['superAdmin'],
    ]);
// delete password request
    Route::delete('users/passwordRequest/delete',[
        'uses'=>'UserController@deletePasswordRequest',
        'as'=>'deletePasswordRequest',
        'middleware'=>'roles',
        'roles'=>['superAdmin'],
    ]);

   Route::group(['middleware'=>'roles','roles'=>['admin','superAdmin']],function (){
       // add user to group
       Route::get('groups/{room}/group_users','ChatController@groupUser')->name('group_user');
       // update user's groups
       Route::get('user/{user}/group_update','UserController@updateGroupsView')->name('updateGroupUserView');
       Route::post('user/{user}/group_updated','UserController@updateGroups')->name('updateGroupUser');
   });
   Route::group(['middleware'=>'roles','roles'=>['superAdmin']],function (){
      Route::get('users/update/requests','UserController@userUpdateRequests')
          ->name('userUpdateRequests');
      Route::get('user/update/password/requests','UserController@userUpdatePasswordRequests')
          ->name('userPasswordRequests');
       Route::get('user/update/groups/requests','UserController@indexUserGroupRequests')
           ->name('indexUserGroupRequests');
       Route::delete('user/update/groups/requests/delete','UserController@deleteGroupRequest')
           ->name('deleteGroupRequest');
   });

});
// request for edit
Route::post('edit-request','UserController@createRequest')->name('createRequest');
// Role Routes
Route::resource('roles','RolesController');
// Last News Routes
Route::resource('lastNews','LastNewsController')->except(['destroy']);
Route::delete('lastNews/{post}/delete','LastNewsController@destroy')->name('lastNews.delete');
// Section Routes
Route::resource('section','SectionController');
// About Routes
Route::resource('about','AboutController');
// Question Routes
Route::resource('questions','FaqController');
// Chat Routes
Route::resource('Chat','ChatController');
Route::get('/chat.show/{id}',[\App\Http\Controllers\ChatController::class, 'show'])->name('groupName');
Route::get('/conve/{code}',[\App\Http\Controllers\UserController::class, 'conversation'])->name('conversation');
Route::get('/D/{id}',function ($id){
    $getById = \App\Models\Chatroom::find($id);
    $getById->delete();
    return redirect()->back()->withstatus(__('Room Deleted'));
});
Route::get('/editRoom/{id}',[\App\Http\Controllers\ChatController::class, 'editRoom'])->name('editRoom');
Route::post('/editRoom/{id}',[\App\Http\Controllers\ChatController::class, 'editRoom'])->name('editRoom');
Route::post('/activeRoom/{id}',[\App\Http\Controllers\ChatController::class, 'activeRoom'])->name('activeRoom');
//private chat route
Route::get('/messages',[\App\Http\Controllers\UserController::class ,'messages'])->name('messages');
// Answers Routes
Route::get('answers/{answer}/show','FaqController@showAnswer')->name('answer.show');
Route::get('answers/{answer}/edit','FaqController@editAnswer')->name('answer.edit');
Route::put('answers/{answer}/update','FaqController@updateAnswer')->name('answer.update');
Route::get('answers/{question}/create','FaqController@createAnswer')->name('answer.create');
Route::post('answers/store','FaqController@storeAnswer')->name('answer.store');
Route::delete('answers/{answer}/delete','FaqController@destroyAnswer')->name('answer.delete');
//procedure types
Route::resource('procedureType', 'ProcedureTypeController');
//student requests
Route::resource('studentRequest', 'StudentRequestController')->except(['index']);
Route::post('studentRequest/forward_to/{studentRequest}', 'StudentRequestController@forward')->name('studentRequest.forward');
Route::post('studentRequest/done/{studentRequest}','StudentRequestController@done')->name('done');
Route::get('studentRequests','StudentRequestController@adminIndex')->name('request.admin');
Route::get('studentRequest',[
    'uses'=>'StudentRequestController@index',
    'as'=>'studentRequest.index',
    'middleware'=>'roles',
    'roles'=>['superAdmin']
]);
//chat request
Route::resource('chatRequests','ChatRequestController');
Route::post('chatRequest/confirm/{chatRequest}','ChatRequestController@confirm')->name('chatRequest.confirm');
// Hdr Routes
Route::resource('hrd','HrdController');
// Groups Routes
Route::resource('groups','UserGroupsController');
//excel
Route::get('file-import-export', 'UserController@fileImportExport');
Route::post('file-import', 'UserController@fileImport')->name('file-import');
Route::get('file-export', 'UserController@fileExport')->name('file-export');
//lang
Route::get('lang/{lang}', 'LanguageController@swap')->name('lang');
Route::post('notify',[\App\Http\Controllers\ChatController::class, 'notification'])->name('notification');
//reports
Route::get('reports','UserController@counter')->name('reports');

app/Models/Hrd.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Hrd extends Model
{
    protected $fillable=[
        'name','name_ar','description','description_ar'
    ];
}

app/Http/Controllers/Api/HrdController.php
<?php

namespace App\Http\Controllers\Api;

use App\Events\notifications\NotificationCreatedEvent;
use App\Http\Controllers\Controller;
use App\Http\Resources\HrdResource;
use App\Models\Hrd;
use App\Models\Notification;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class HrdController extends Controller
{
    public function __construct()
    {
        $this->middleware('guest')->only('index');
    }

    public function index()
    {
        return HrdResource::collection(Hrd::paginate(10));
    }


    public function create()
    {

    }


    public function store(Request $request)
    {
        $validator=Validator::make($request->all(),[
            'name'=>'required|string',
            'name_ar'=>'required|string',
            'description'=>'required|string',
            'description_ar'=>'required|string'
        ]);
        if ($validator->fails()){
            return response()->json($validator->errors(),200);
        }
        $hdrcontent=new Hrd();
        $hdrcontent->name=$request->name;
        $hdrcontent->name_ar=$request->name_ar;
        $hdrcontent->description=$request->description;
        $hdrcontent->description_ar=$request->description_ar;
        $hdrcontent->save();
        if ($hdrcontent) {
            //notification structure
            $message = 'New HR section is added !';
            $users=User::all()->except(['1','2']);
            foreach ($users as $receiver){
                $receiver_id=$receiver->id;
                $notification = Notification::create([
                    'title' => 'HR Section',
                    'text' => $message,
                    'user_id'=>$receiver_id,
                ]);
                event(new NotificationCreatedEvent($notification,$receiver_id));
            }
            return response()->json('Content Created',200);
        }

    }


    public function show(Hrd $hrd)
    {
        return HrdResource::make($hrd);
    }

    public function edit(Hrd $hrd)
    {
        return HrdResource::make($hrd);
    }


    public function update(Request $request, Hrd $hrd)
    {
        $validator=Validator::make($request->all(),[
            'name'=>'string',
            'name_ar'=>'string',
            'description'=>'string',
            'description_ar'=>'string'
        ]);
        if ($validator->fails()){
            return response()->json($validator->errors(),200);
        }
        $hrd->name=$request->name;
        $hrd->name_ar=$request->name_ar;
        $hrd->description=$request->description;
        $hrd->description_ar=$request->description_ar;
        $hrd->save();
        return response()->json('Content Updated',200);
    }


    public function destroy(Hrd $hrd)
    {
        $hrd->delete();
        return response()->json('Content Deleted',200);
    }
}

app/Http/Controllers/HrdController.php
<?php

namespace App\Http\Controllers;

use App\Events\notifications\NotificationCreatedEvent;
use App\Models\Hrd;
use App\Models\Notification;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class HrdController extends Controller
{

    public function index()
    {
        $hrdcontent=Hrd::orderBy('created_at','desc')->get();
        return view('hrd.index',compact('hrdcontent'));
    }


    public function create()
    {
        return view('hrd.create');
    }


    public function store(Request $request)
    {
        $validator=Validator::make($request->all(),[
           'name'=>'required|string',
           'name_ar'=>'required|string',
           'description'=>'required|string',
           'description_ar'=>'required|string'
        ]);
        $hdrcontent=new Hrd();
        $hdrcontent->name=$request->name;
        $hdrcontent->name_ar=$request->name_ar;
        $hdrcontent->description=$request->description;
        $hdrcontent->description_ar=$request->description_ar;
        $hdrcontent->save();
        if ($hdrcontent) {
            //notification structure
            $message = 'New HR section is added !';
            $users=User::all()->except(['1','2']);
            foreach ($users as $receiver){
                $receiver_id=$receiver->id;
                $notification = Notification::create([
                    'title' => 'HR Section',
                    'text' => $message,
                    'user_id'=>$receiver_id,
                ]);
                event(new NotificationCreatedEvent($notification,$receiver_id));
            }
            return redirect()->back()->withstatus(__('alerts.backend.hrd.created'));
        }

    }


    public function show(Hrd $hrd)
    {
        return view('hrd.show',compact('hrd'));
    }


    public function edit(Hrd $hrd)
    {
        return view('hrd.edit',compact('hrd'));
    }


    public function update(Request $request, Hrd $hrd)
    {
        $validator=Validator::make($request->all(),[
            'name'=>'string',
            'name_ar'=>'string',
            'description'=>'string',
            'description_ar'=>'string'
        ]);
        $hrd->name=$request->name;
        $hrd->name_ar=$request->name_ar;
        $hrd->description=$request->description;
        $hrd->description_ar=$request->description_ar;
        $hrd->save();
        return redirect()->back()->withstatus(__('alerts.backend.hrd.updated'));

    }

    public function destroy(Hrd $hrd)
    {
        $hrd->delete();
        return redirect()->back()->withstatus(__('alerts.backend.hrd.deleted'));
    }
}

resources/views/hrd/create.blade.php
@extends('layouts.app', ['title' => __('Create Hrd')])

@section('content')
    @include('hrd.partials.header', [
        'class' => 'col-lg-12'
    ])
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-8 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <h3 class="col-12 mb-0">@lang('labels.backend.access.hrd.create')</h3>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{route('hrd.store')}}" method="post" enctype="multipart/form-data">
                            @method('POST')
                            @csrf
                            <h6 class="heading-small text-muted mb-4">@lang('labels.backend.access.hrd.hrd-information')</h6>
                            <div class="col-12">
                                @if (session('status'))
                                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                                        {{ session('status') }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @endif
                            </div>
                            <div class="col-12">
                                @if($errors->any())
                                    @foreach($errors->all() as $error)
                                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                            {{$error}}
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                    @endforeach
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                <label for="name">@lang('labels.backend.access.hrd.name')</label>
                                <input name="name" type="text"
                                       class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" id="name"
                                       placeholder="name"
                                       required>
                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('name_ar') ? ' has-danger' : '' }}">
                                <label for="name">@lang('labels.backend.access.hrd.arabic-name')</label>
                                <input name="name_ar" type="text"
                                       class="form-control form-control-alternative{{ $errors->has('name_ar') ? ' is-invalid' : '' }}" id="name"
                                       placeholder="الاسم"
                                       required>
                                @if ($errors->has('name_ar'))
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name_ar') }}</strong>
                                        </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('description') ? ' has-danger' : '' }}">
                                <label for="description">@lang('labels.backend.access.hrd.description')</label>
                                <textarea name="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" id="post" rows="3" ></textarea>
                                @if ($errors->has('description'))
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('description') }}</strong>
                                        </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('description_ar') ? ' has-danger' : '' }}">
                                <label for="description">ِ@lang('labels.backend.access.hrd.description-arabic')</label>
                                <textarea name="description_ar" class="form-control{{ $errors->has('description_ar') ? ' is-invalid' : '' }}" id="post" rows="3" ></textarea>
                                @if ($errors->has('description_ar'))
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('description_ar') }}</strong>
                                        </span>
                                @endif
                            </div>
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-success btn-lg ">@lang('buttons.general.crud.create')</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/hrd/edit.blade.php
@extends('layouts.app', ['title' => __('Edit Hrd')])

@section('content')
    @include('hrd.partials.header', [
        'class' => 'col-lg-12'
    ])
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-8 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <h3 class="col-12 mb-0">@lang('labels.backend.access.hrd.edit')</h3>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{route('hrd.update',$hrd)}}" method="post" enctype="multipart/form-data">
                            @method('PUT')
                            @csrf
                            <h6 class="heading-small text-muted mb-4">@lang('labels.backend.access.hrd.hrd-information')</h6>
                            <div class="col-12">
                                @if (session('status'))
                                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                                        {{ session('status') }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @endif
                            </div>
                            <div class="col-12">
                                @if($errors->any())
                                    @foreach($errors->all() as $error)
                                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                            {{$error}}
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                    @endforeach
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                <label for="name">@lang('labels.backend.access.hrd.name')</label>
                                <input name="name" type="text"
                                       class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" id="name"
                                       placeholder="{{$hrd->name}}"
                                       value="{{$hrd->name}}"
                                       required>
                                @if ($errors->has('name'))
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('name_ar') ? ' has-danger' : '' }}">
                                <label for="name">@lang('labels.backend.access.hrd.arabic-name')</label>
                                <input name="name_ar" type="text"
                                       class="form-control form-control-alternative{{ $errors->has('name_ar') ? ' is-invalid' : '' }}" id="name"
                                       placeholder="{{$hrd->name_ar}}"
                                       value="{{$hrd->name_ar}}"
                                       required>
                                @if ($errors->has('name_ar'))
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name_ar') }}</strong>
                                        </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('description') ? ' has-danger' : '' }}">
                                <label for="description">@lang('labels.backend.access.hrd.description')</label>
                                <textarea name="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" id="post" rows="3" required>{{$hrd->description}}</textarea>
                                @if ($errors->has('description'))
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('description') }}</strong>
                                        </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('description_ar') ? ' has-danger' : '' }}">
                                <label for="description@lang('labels.backend.access.hrd.description-arabic')</label>
                                <textarea name="description_ar" class="form-control{{ $errors->has('description_ar') ? ' is-invalid' : '' }}" id="post" rows="3" required>{{$hrd->description_ar}}</textarea>
                                @if ($errors->has('description_ar'))
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('description_ar') }}</strong>
                                        </span>
                                @endif
                            </div>
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-success btn-lg ">@lang('buttons.general.crud.edit')</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/hrd/index.blade.php
@extends('layouts.app', ['title' => __('Hrd')])
@section('content')
    <div class="main-content">
        <div class="header bg-gradient-orange pb-8 pt-5 pt-md-8">
            <div class="container-fluid">
                <div class="header-body">
                    <!-- Card stats -->
                </div>
            </div>
        </div>
        <div class="container-fluid mt--7">
            <div class="row">
                <div class="col">
                    <div class="card shadow">
                        <div class="card-header border-0">
                            <div class="row align-items-center">
                                <div class="col-8">
                                    <h3 class="mb-0">HRD</h3>
                                </div>
                                <div class="col-4 text-right">
                                    <a href="{{route('hrd.create')}}" class="btn btn-sm btn-primary">@lang('buttons.general.crud.create')</a>
                                </div>
                            </div>
                        </d
                        <div class="col-12">
                            @if (session('status'))
                                <div class="alert alert-success alert-dismissible fade show" role="alert">
                                    {{ session('status') }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            @endif
                        </div>
                        <div class="col-12">
                            @if($errors->any())
                                @foreach($errors->all() as $error)
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        {{$error}}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @endforeach
                            @endif
                        </div>
                        <div class="table-responsive">
                            <table id="example" class="table align-items-center table-flush">
                                <thead class="thead-light">
                                <tr>
                                    <th scope="col">@lang('labels.backend.access.hrd.name')</th>
                                    <th scope="col">@lang('labels.backend.access.hrd.arabic-name')</th>
                                    <th scope="col">@lang('labels.backend.access.hrd.create-date')</th>
                                    <th scope="col"></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($hrdcontent as $hrd)
                                    <tr>
                                        <td>
                                            <a href="{{route('hrd.show',$hrd)}}">
                                                {{$hrd->name}}
                                            </a>
                                        </td>
                                        <td>
                                            {{$hrd->name_ar}}
                                        </td>
                                        <td>
                                            {{$hrd->created_at->diffForHumans()}}
                                        </td>
                                        <td class="text-right">
                                            <div class="dropdown">
                                                <a class="btn btn-sm btn-icon-only text-light" href="#" role="button"
                                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="fas fa-ellipsis-v"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                    <a class="dropdown-item" href="{{route('hrd.edit',$hrd)}}">@lang('buttons.general.crud.edit')</a>
                                                    <form action="{{route('hrd.destroy',$hrd)}}" method="post">
                                                        @method('DELETE')
                                                        @csrf
                                                        <button type="submit" class="dropdown-item">@lang('buttons.general.crud.delete')</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="card-footer py-4">
                            <nav class="d-flex justify-content-end" aria-label="...">
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            @include('layouts.footers.auth')
        </div>
    </div>
@endsection