routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();
Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController');
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
// show request
    Route::get('users/show-request/{user}', [
        'uses'=>'UserController@showRequest',
        'as'=>'showRequest',
        'middleware'=>'roles',
        'roles'=>['superAdmin'],
    ]);
//user's password edit request
    Route::put('user/password/edit', [
        'uses'=>'UserController@editPassword',
        'as'=>'edit.password',
        'middleware'=>'roles',
        'roles'=>['admin','superAdmin'],
    ]);
    Route::put('user/password/update', [
        'uses'=>'UserController@updatePassword',
        'as'=>'update.password',
        'middleware'=>'roles',
        'roles'=>['superAdmin'],
    ]);
// delete edit request
    Route::delete('users/editRequest/{id}/delete', [
        'uses'=>'UserController@deleteRequest',
        'as'=>'deleteRequest',
        'middleware'=>'roles',
        'roles'=>['superAdmin'],
    ]);
//show user group request
    Route::get('group/{user}/request', [
        'uses'=>'UserController@userGroupsRequest',
        'as'=>'userGroupsRequest',
        'middleware'=>'roles',
        'roles'=>['superAdmin'],
    ]);
// Approve request update group
    Route::post('group/request/approve', [
        'uses'=>'UserController@activeUserGroups',
        'as'=>'approve.request',
        'middleware'=>'roles',
        'roles'=>['superAdmin'],
    ]);
// delete password request
    Route::delete('users/passwordRequest/delete',[
        'uses'=>'UserController@deletePasswordRequest',
        'as'=>'deletePasswordRequest',
        'middleware'=>'roles',
        'roles'=>['superAdmin'],
    ]);

   Route::group(['middleware'=>'roles','roles'=>['admin','superAdmin']],function (){
       // add user to group
       Route::get('groups/{room}/group_users','ChatController@groupUser')->name('group_user');
       // update user's groups
       Route::get('user/{user}/group_update','UserController@updateGroupsView')->name('updateGroupUserView');
       Route::post('user/{user}/group_updated','UserController@updateGroups')->name('updateGroupUser');
   });
   Route::group(['middleware'=>'roles','roles'=>['superAdmin']],function (){
      Route::get('users/update/requests','UserController@userUpdateRequests')
          ->name('userUpdateRequests');
      Route::get('user/update/password/requests','UserController@userUpdatePasswordRequests')
          ->name('userPasswordRequests');
       Route::get('user/update/groups/requests','UserController@indexUserGroupRequests')
           ->name('indexUserGroupRequests');
       Route::delete('user/update/groups/requests/delete','UserController@deleteGroupRequest')
           ->name('deleteGroupRequest');
   });

});
// request for edit
Route::post('edit-request','UserController@createRequest')->name('createRequest');
// Role Routes
Route::resource('roles','RolesController');
// Last News Routes
Route::resource('lastNews','LastNewsController')->except(['destroy']);
Route::delete('lastNews/{post}/delete','LastNewsController@destroy')->name('lastNews.delete');
// Section Routes
Route::resource('section','SectionController');
// About Routes
Route::resource('about','AboutController');
// Question Routes
Route::resource('questions','FaqController');
// Chat Routes
Route::resource('Chat','ChatController');
Route::get('/chat.show/{id}',[\App\Http\Controllers\ChatController::class, 'show'])->name('groupName');
Route::get('/conve/{code}',[\App\Http\Controllers\UserController::class, 'conversation'])->name('conversation');
Route::get('/D/{id}',function ($id){
    $getById = \App\Models\Chatroom::find($id);
    $getById->delete();
    return redirect()->back()->withstatus(__('Room Deleted'));
});
Route::get('/editRoom/{id}',[\App\Http\Controllers\ChatController::class, 'editRoom'])->name('editRoom');
Route::post('/editRoom/{id}',[\App\Http\Controllers\ChatController::class, 'editRoom'])->name('editRoom');
Route::post('/activeRoom/{id}',[\App\Http\Controllers\ChatController::class, 'activeRoom'])->name('activeRoom');
//private chat route
Route::get('/messages',[\App\Http\Controllers\UserController::class ,'messages'])->name('messages');
// Answers Routes
Route::get('answers/{answer}/show','FaqController@showAnswer')->name('answer.show');
Route::get('answers/{answer}/edit','FaqController@editAnswer')->name('answer.edit');
Route::put('answers/{answer}/update','FaqController@updateAnswer')->name('answer.update');
Route::get('answers/{question}/create','FaqController@createAnswer')->name('answer.create');
Route::post('answers/store','FaqController@storeAnswer')->name('answer.store');
Route::delete('answers/{answer}/delete','FaqController@destroyAnswer')->name('answer.delete');
//procedure types
Route::resource('procedureType', 'ProcedureTypeController');
//student requests
Route::resource('studentRequest', 'StudentRequestController')->except(['index']);
Route::post('studentRequest/forward_to/{studentRequest}', 'StudentRequestController@forward')->name('studentRequest.forward');
Route::post('studentRequest/done/{studentRequest}','StudentRequestController@done')->name('done');
Route::get('studentRequests','StudentRequestController@adminIndex')->name('request.admin');
Route::get('studentRequest',[
    'uses'=>'StudentRequestController@index',
    'as'=>'studentRequest.index',
    'middleware'=>'roles',
    'roles'=>['superAdmin']
]);
//chat request
Route::resource('chatRequests','ChatRequestController');
Route::post('chatRequest/confirm/{chatRequest}','ChatRequestController@confirm')->name('chatRequest.confirm');
// Hdr Routes
Route::resource('hrd','HrdController');
// Groups Routes
Route::resource('groups','UserGroupsController');
//excel
Route::get('file-import-export', 'UserController@fileImportExport');
Route::post('file-import', 'UserController@fileImport')->name('file-import');
Route::get('file-export', 'UserController@fileExport')->name('file-export');
//lang
Route::get('lang/{lang}', 'LanguageController@swap')->name('lang');
Route::post('notify',[\App\Http\Controllers\ChatController::class, 'notification'])->name('notification');
//reports
Route::get('reports','UserController@counter')->name('reports');

app/Models/Question.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    protected $fillable=[
        'question','answer'
    ];
    public function answers(){
        return $this->hasMany('App\Models\Answer');
    }
}

resources/views/questions/create.blade.php
@extends('layouts.app', ['name' => __('Create New Question')])

@section('content')
    @include('questions.partials.header', [

        'class' => 'col-lg-12'
    ])
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-8 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <h3 class="col-12 mb-0">@lang('labels.backend.access.faq.create')</h3>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{route('questions.store')}}" method="post" enctype="multipart/form-data">
                            @method('POST')
                            @csrf
                            <h6 class="heading-small text-muted mb-4">@lang('labels.backend.access.faq.question')</h6>
                            <div class="col-12">
                                @if (session('status'))
                                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                                        {{ session('status') }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @endif
                            </div>
                            <div class="col-12">
                                @if($errors->any())
                                    @foreach($errors->all() as $error)
                                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                            {{$error}}
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                    @endforeach
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('question') ? ' has-danger' : '' }}">
                                <label for="question">@lang('labels.backend.access.faq.question')</label>
                                <textarea name="question" type="text"
                                          class="form-control form-control-alternative{{ $errors->has('question') ? ' is-invalid' : '' }}"
                                          id="question"
                                          placeholder="question"
                                          ></textarea>
                                @if ($errors->has('question'))
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('question') }}</strong>
                                        </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('question_ar') ? ' has-danger' : '' }}">
                                <label for="question_ar">@lang('labels.backend.access.faq.arabic-question')</label>
                                <textarea name="question_ar" type="text"
                                          class="form-control form-control-alternative{{ $errors->has('question') ? ' is-invalid' : '' }}"
                                          id="question"
                                          placeholder="السؤال"
                                          ></textarea>
                                @if ($errors->has('question_ar'))
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('question_ar') }}</strong>
                                        </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('answer') ? ' has-danger' : '' }}">
                                <label for="answer">@lang('labels.backend.access.faq.answer')</label>
                                <textarea name="answer" type="text"
                                          class="form-control form-control-alternative{{ $errors->has('answer') ? ' is-invalid' : '' }}"
                                          id="answer"
                                          placeholder="answer"
                                          ></textarea>
                                @if ($errors->has('answer'))
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('answer') }}</strong>
                                        </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('answer_ar') ? ' has-danger' : '' }}">
                                <label for="answer_ar">@lang('labels.backend.access.faq.arabic-answer')</label>
                                <textarea name="answer_ar" type="text"
                                          class="form-control form-control-alternative{{ $errors->has('answer_ar') ? ' is-invalid' : '' }}"
                                          id="answer"
                                          placeholder="الجواب"
                                          ></textarea>
                                @if ($errors->has('answer_ar'))
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('answer_ar') }}</strong>
                                        </span>
                                @endif
                            </div>
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-success btn-lg">@lang('buttons.general.crud.create')</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app', ['name' => __('Edit Question')])

@section('content')
    @include('questions.partials.header', [

        'class' => 'col-lg-12'
    ])
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-8 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <h3 class="col-12 mb-0">@lang('labels.backend.access.faq.edit')</h3>
                        </div>
                    </div>
                    <div class="card-body">
                        <form action="{{route('questions.update',$question)}}" method="post"
                              enctype="multipart/form-data">
                            @method('PUT')
                            @csrf
                            <h6 class="heading-small text-muted mb-4">@lang('labels.backend.access.faq.question')</h6>
                            <div class="col-12">
                                @if (session('status'))
                                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                                        {{ session('status') }}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @endif
                            </div>
                            <div class="col-12">
                                @if($errors->any())
                                    @foreach($errors->all() as $error)
                                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                            {{$error}}
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                    @endforeach
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('question') ? ' has-danger' : '' }}">
                                <label for="content">@lang('labels.backend.access.faq.question')</label>
                                <textarea name="question" type="text"
                                          class="form-control form-control-alternative{{ $errors->has('question') ? ' is-invalid' : '' }}"
                                          id="content"
                                          placeholder="Description"
                                          required>{{$question->question}}</textarea>
                                @if ($errors->has('question'))
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('question') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('question_ar') ? ' has-danger' : '' }}">
                                <label for="content">@lang('labels.backend.access.faq.arabic-question')</label>
                                <textarea name="question_ar" type="text"
                                          class="form-control form-control-alternative{{ $errors->has('question_ar') ? ' is-invalid' : '' }}"
                                          id="content_ar"
                                          placeholder="السؤال"
                                          required>{{$question->question_ar}}</textarea>
                                @if ($errors->has('question_ar'))
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('question_ar') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('answer') ? ' has-danger' : '' }}">
                                <label for="content">@lang('labels.backend.access.faq.answer')</label>
                                <textarea name="answer" type="text"
                                          class="form-control form-control-alternative{{ $errors->has('answer') ? ' is-invalid' : '' }}"
                                          id="content"
                                          placeholder="Description"
                                          required>{{$question->answer}}</textarea>
                                @if ($errors->has('answer'))
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('answer') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="form-group{{ $errors->has('answer_ar') ? ' has-danger' : '' }}">
                                <label for="content">@lang('labels.backend.access.faq.arabic-answer')</label>
                                <textarea name="answer_ar" type="text"
                                          class="form-control form-control-alternative{{ $errors->has('answer_ar') ? ' is-invalid' : '' }}"
                                          id="content"
                                          placeholder="الجواب"
                                          required>{{$question->answer_ar}}</textarea>
                                @if ($errors->has('answer_ar'))
                                    <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('answer_ar') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-success btn-lg ">@lang('buttons.general.crud.edit')</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app', ['title' => __('Questions')])
@section('content')
    <div class="main-content">
        <div class="header bg-gradient-orange pb-8 pt-5 pt-md-8">
            <div class="container-fluid">
                <div class="header-body">
                    <!-- Card stats -->
                </div>
            </div>
        </div>
        <div class="container-fluid mt--7">
            <div class="row">
                <div class="col">
                    <div class="card shadow">
                        <div class="card-header border-0">
                            <div class="row align-items-center">
                                <div class="col-8">
                                    <h3 class="mb-0">@lang('labels.backend.access.faq.question')</h3>
                                </div>
                                <div class="col-4 text-right">
                                    <a href="{{route('questions.create')}}" class="btn btn-sm btn-primary">@lang('buttons.general.crud.create')</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            @if (session('status'))
                                <div class="alert alert-success alert-dismissible fade show" role="alert">
                                    {{ session('status') }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            @endif
                        </div>
                        <div class="col-12">
                            @if($errors->any())
                                @foreach($errors->all() as $error)
                                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                        {{$error}}
                                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                @endforeach
                            @endif
                        </div>
                        <div class="table-responsive">
                            <table id="example" class="table align-items-center table-flush">
                                <thead class="thead-light">
                                <tr>
                                    <th scope="col">@lang('labels.backend.access.faq.question')</th>
                                    <th scope="col">@lang('labels.backend.access.faq.arabic-question')</th>
                                    <th scope="col">@lang('labels.backend.access.faq.answer')</th>
                                    <th scope="col">@lang('labels.backend.access.faq.arabic-answer')</th>
                                    <th scope="col">@lang('labels.backend.access.faq.create-date')</th>
                                    <th scope="col"></th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($questions as $question)
                                    <tr>
                                        <td>
                                            <a href="{{route('questions.show',$question)}}">
                                                {{$question->question}}
                                            </a>
                                        </td>
                                        <td>
                                            {{$question->question_ar}}
                                        </td>
                                        <td>
                                            {{$question->answer}}
                                        </td>
                                        <td>
                                            {{$question->answer_ar}}
                                        </td>
                                        <td>
                                            {{$question->created_at->diffForHumans()}}
                                        </td>
                                        <td class="text-right">
                                            <div class="dropdown">
                                                <a class="btn btn-sm btn-icon-only text-light" href="#" role="button"
                                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="fas fa-ellipsis-v"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                    <a class="dropdown-item"
                                                       href="{{route('questions.edit',$question)}}">@lang('buttons.general.crud.edit')</a>
                                                    <form action="{{route('questions.destroy',$question)}}"
                                                          method="post">
                                                        @method('DELETE')
                                                        @csrf
                                                        <button type="submit" class="dropdown-item">@lang('buttons.general.crud.delete')</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="card-footer py-4">
                            <nav class="d-flex justify-content-end" aria-label="...">
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            @include('layouts.footers.auth')
        </div>
    </div>
@endsection